name: Update Repo Count Badges

on:
  schedule:
    - cron: "0 0 1 * *"  # At 00:00 on the 1st of every month
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Fetch repo stats
        id: repo_data
        env:
          GH_TOKEN: ${{ secrets.METRICS_TOKEN }}
        run: |
          GH_USER="Cuppixx"
          GH_API="https://api.github.com/users/$GH_USER"
      
          response=$(curl -s $GH_API)
          repos=$(echo "$response" | jq '.public_repos')
      
          # Use METRICS_TOKEN to authenticate with gh for private repos
          echo "$GH_TOKEN" | gh auth login --with-token
      
          total_repos=$(gh repo list $GH_USER --limit 1000 --json name --jq 'length')
      
          echo "PUBLIC_REPO_COUNT=$repos" >> $GITHUB_ENV
          echo "REPO_COUNT=$total_repos" >> $GITHUB_ENV

      - name: Replace placeholders in README
        run: |
          sed -i "s/<REPO_COUNT>/${{ env.REPO_COUNT }}/g" README.md
          sed -i "s/<PUBLIC_REPO_COUNT>/${{ env.PUBLIC_REPO_COUNT }}/g" README.md

      - name: Commit and push changes with PAT
        env:
          GIT_TOKEN: ${{ secrets.METRICS_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          
          git add README.md
          git commit -m "chore: update repo badges in README" || echo "No changes to commit"
          git push https://Cuppixx:${GIT_TOKEN}@github.com/Cuppixx/Cuppixx.git HEAD:main
