name: Update Repo Count Badges

on:
  schedule:
    - cron: "0 0 1 * *" # At 00:00 on the 1st of every month
  workflow_dispatch:
  
permissions:
  contents: write
  
jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Fetch repo stats
        id: repo_data
        env:
          GH_TOKEN: ${{ secrets.METRICS_TOKEN }}
        run: |
          GH_USER="Cuppixx"
          
          public_count=$(gh repo list $GH_USER --limit 1000 --visibility public --json name --jq 'length')
          echo "PUBLIC_REPO_COUNT=$public_count" >> $GITHUB_ENV
          
          private_count=$(gh repo list $GH_USER --limit 1000 --visibility private --json name --jq 'length')
          total_count=$((public_count + private_count))
          echo "REPO_COUNT=$total_count" >> $GITHUB_ENV
          
          gist_count=$(gh api user/gists --paginate --jq 'length')
          echo "GIST_COUNT=$gist_count" >> $GITHUB_ENV
          
          packages_query='
          query($login: String!) {
            user(login: $login) {
              packages(first: 1000) {
                totalCount
              }
            }
          }'
          packages_count=$(gh api graphql -f query="$packages_query" -f login="$GH_USER" --jq '.data.user.packages.totalCount')
          echo "PACKAGES_COUNT=$packages_count" >> $GITHUB_ENV
          
          # Debug output
          echo "Repos: $total_count" 
          echo "Public Repos: $public_count"
          echo "Gists: $gist_count"
          echo "Packages: $packages_count"
          
      - name: Update badge numbers in README
        run: |
          sed -i "s/Repos-[0-9]\+/Repos-${{ env.REPO_COUNT }}/g" README.md
          sed -i "s/Public%20Repos-[0-9]\+/Public%20Repos-${{ env.PUBLIC_REPO_COUNT }}/g" README.md
          sed -i "s/Gists-[0-9]\+/Gists-${{ env.GIST_COUNT }}/g" README.md
          sed -i "s/Packages-[0-9]\+/Packages-${{ env.PACKAGES_COUNT }}/g" README.md
          
      - name: Commit and push changes with PAT
        env:
          GIT_TOKEN: ${{ secrets.METRICS_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "chore: update repo badges in README [skip ci]" || echo "No changes to commit"
          git push https://Cuppixx:${GIT_TOKEN}@github.com/Cuppixx/Cuppixx.git HEAD:main
