name: Update Repo Count Badges
on:
  schedule:
    - cron: "0 0 1 * *" # At 00:00 on the 1st of every month
  workflow_dispatch:
permissions:
  contents: write
jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Fetch repo stats
        id: repo_data
        env:
          GH_TOKEN: ${{ secrets.METRICS_TOKEN }}
        run: |
          GH_USER="Cuppixx"
          
          # Get counts using gh CLI
          public_count=$(gh repo list $GH_USER --limit 1000 --visibility public --json name --jq 'length')
          private_count=$(gh repo list $GH_USER --limit 1000 --visibility private --json name --jq 'length')
          total_count=$((public_count + private_count))
          
          echo "PUBLIC_REPO_COUNT=$public_count" >> $GITHUB_ENV
          echo "REPO_COUNT=$total_count" >> $GITHUB_ENV
          
          # Debug output
          echo "Public repos: $public_count"
          echo "Private repos: $private_count" 
          echo "Total repos: $total_count"
          
      - name: Update badge numbers in README
        run: |
          # Update total repos badge (matches: Repos-[number]-blue)
          sed -i "s/Repos-[0-9]\+/Repos-${{ env.REPO_COUNT }}/g" README.md
          
          # Update public repos badge (matches: Public%20Repos-[number]-blue)
          sed -i "s/Public%20Repos-[0-9]\+/Public%20Repos-${{ env.PUBLIC_REPO_COUNT }}/g" README.md
          
      - name: Commit and push changes with PAT
        env:
          GIT_TOKEN: ${{ secrets.METRICS_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "chore: update repo badges in README [skip ci]" || echo "No changes to commit"
          git push https://Cuppixx:${GIT_TOKEN}@github.com/Cuppixx/Cuppixx.git HEAD:main
